### ISSUE TITLE
Startup errors!

### ISSUE THREAD

**Issue by yujiaming2016** [opera/logpeck#35]
Open database error: open /var/logpeck/logpeck.db: no such file or directory.panic: open /var/logpeck/logpeck.db: no such file or directory

**Comment by yujiaming2016** [comment]
已经解决了，谢谢！但是我装了logpeck-kibana-plugin后，打开是如下页面：
<img width="1016" alt="default" src="https://user-images.githubusercontent.com/23226718/43620595-1b9ca232-9706-11e8-83e4-729ce0a8165e.png">
当点击“add”按钮时，后台报错：
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'total' of undefined
    at Wreck.post (/usr/local/nebula/kibana-5.5.2-linux-x86_64/plugins/logpeck/server/routes/example.js:1042:37)
    at /usr/local/nebula/kibana-5.5.2-linux-x86_64/node_modules/wreck/lib/index.js:465:20
    at finish (/usr/local/nebula/kibana-5.5.2-linux-x86_64/node_modules/wreck/lib/index.js:294:20)
    at wrapped (/usr/local/nebula/kibana-5.5.2-linux-x86_64/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/usr/local/nebula/kibana-5.5.2-linux-x86_64/node_modules/wreck/lib/index.js:356:16)
    at g (events.js:292:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:512:14)
    at afterWrite (_stream_writable.js:386:3)
    at _combinedTickCallback (internal/process/next_tick.js:86:20)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by xupeilin** [comment]
https://github.com/opera/logpeck-kibana-plugin/issues/24
